// Major cities and municipalities in Ontario, Canada
// Stored as "City, ON" to match job location format
export const ONTARIO_CITIES: string[] = [
  'Ajax, ON',
  'Aurora, ON',
  'Barrie, ON',
  'Belleville, ON',
  'Brampton, ON',
  'Brantford, ON',
  'Brockville, ON',
  'Burlington, ON',
  'Caledon, ON',
  'Cambridge, ON',
  'Chatham, ON',
  'Clarington, ON',
  'Cobourg, ON',
  'Collingwood, ON',
  'Cornwall, ON',
  'East Gwillimbury, ON',
  'Fort Erie, ON',
  'Georgina, ON',
  'Grimsby, ON',
  'Guelph, ON',
  'Halton Hills, ON',
  'Hamilton, ON',
  'Huntsville, ON',
  'Innisfil, ON',
  'Kawartha Lakes, ON',
  'King, ON',
  'Kingston, ON',
  'Kitchener, ON',
  'Lincoln, ON',
  'London, ON',
  'Markham, ON',
  'Midland, ON',
  'Milton, ON',
  'Mississauga, ON',
  'Newmarket, ON',
  'Niagara Falls, ON',
  'Niagara-on-the-Lake, ON',
  'North Bay, ON',
  'Oakville, ON',
  'Orangeville, ON',
  'Orillia, ON',
  'Oshawa, ON',
  'Ottawa, ON',
  'Owen Sound, ON',
  'Pelham, ON',
  'Penetanguishene, ON',
  'Peterborough, ON',
  'Pickering, ON',
  'Port Colborne, ON',
  'Port Hope, ON',
  'Richmond Hill, ON',
  'Sarnia, ON',
  'Sault Ste. Marie, ON',
  'Scugog, ON',
  'St. Catharines, ON',
  'St. Thomas, ON',
  'Stouffville, ON',
  'Stratford, ON',
  'Greater Sudbury, ON',
  'Thunder Bay, ON',
  'Thorold, ON',
  'Timmins, ON',
  'Toronto, ON',
  'Uxbridge, ON',
  'Vaughan, ON',
  'Wasaga Beach, ON',
  'Waterloo, ON',
  'Welland, ON',
  'Whitby, ON',
  'Windsor, ON',
  'Woodstock, ON',
]
